version: '3'

services:
  db:
    container_name: memories_db
    image: postgres:12.4
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4:4.26
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db
    links:
      - db:pgsql-server
    env_file:
      - .env
    ports:
      - ${PG_ADMIN_PORT}:80
  redis:
    image: bitnami/redis:latest

    ports:
      - ${REDIS_PORT}:6379

    environment:
      - ALLOW_EMPTY_PASSWORD=yes